### ISSUE TITLE
Quasi periodic kernel

### ISSUE THREAD

**Issue by j-faria** [jdavidrcamacho/mini-frame#5]
```python
class QuasiPeriodic(kernel):
    .....
    def __call__(self, r):
        f1 = r
        f2 = self.ell_p**2
        f3 = self.ell_e**2
        f4 = self.period
        
        f5 = np.sin(np.pi*f1/f4)
        # shouldn't this
        return np.exp( -(2.0*f5*f5/f2) -0.5*f1/f3 )
        # be this?
        return np.exp( -(2.0*f5*f5/f2) -0.5*f1*f1/f3 )
```

**Comment by jdavidrcamacho** [comment]
Yes! You're correct

**Comment by j-faria** [comment]
Dammit!
Then I think the derivatives are wrong too...

**Comment by jdavidrcamacho** [comment]
No! we're lucky it doesn't do mush damage :D 

It's just the exponential because the derivatives I made on MAXIMA are correct (including the exponential expression)
I just forget to add an f1 when writing the exponential on python and since it apppears in all the derivatives I made ctrl+c ctrl+v making the same mistake everywhere on the QP kernel. We just have do add an f1 in every exponential and its good :D

**Comment by jdavidrcamacho** [comment]
I'm doing it now and then I'll push it to github

**Comment by j-faria** [comment]
Great!

**Comment by jdavidrcamacho** [comment]
Done! 

I'm going to think and change the documentation of the derivatives if necessary because I'm not sure if it correct to call "second derivative in order to t1t1 t2t2" and stuff like that., but I need to review the course I had in partial derivatives to remember what is the correct way to call them xD
